### ISSUE TITLE
Certification test failed

### ISSUE THREAD

**Issue by mixturify** [microsoft/microsoft-ui-xaml#1780]
**Describe the bug**
When creating release app package, the certification test failed

**Steps to reproduce the bug**
VS 2019 > UWP App > Publish > Create App Package

**Expected behavior**
Validating app from the certification test.

**Screenshots**
![image](https://user-images.githubusercontent.com/1378727/71255588-972d0800-232e-11ea-9f2d-a1de501c9414.png)

**Version Info**
Latest Windows 10 version 

NuGet package version: 
Microsoft.UI.XAML 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**
Prior Microsoft.UI.XAML version (2.2) work without any problem!
In the past I was that issue because I build also with ARM64, maybe it's related!

**Comment by ranjeshj** [comment]
@mixturify Can you check your app manifest file and see if there are multiple entries for Microsoft.UI.Xaml ?

**Comment by mixturify** [comment]
@ranjeshj hi, there is just 1 entry. Anyway the packages are still made. Maybe It will still pass the store certification.

**Comment by ranjeshj** [comment]
Are you able to reproduce this with a blank uwp app ? Can you share the version of VS19 you are using ?

**Comment by jevansaks** [comment]
Duplicate of #1747

**Comment by mixturify** [comment]
I've made an blank app and worked.

Then, I just made a clean up the bin / obj folders of the apps, updated again the nugets packages and everything work good now. I don't know, maybe it's random, maybe something from csproject settings. I was not aware about the other ticket #1747 but anyway for resolving that strange bug, just clean up the app generated files!

**Comment by ThE-TiGeR** [comment]
I have exactly the same problem. I allready cleaned my project and did a full rebuild.
I am using VS2019 16.4.2, Windows App Certification Kit 10.0.0.18362.1
Was there a solution found for this?

![image](https://user-images.githubusercontent.com/4369528/72107411-8b32d580-3331-11ea-95d7-c9f84cbbe4dd.png)

**Comment by StephenLPeters** [comment]
> I have exactly the same problem. I allready cleaned my project and did a full rebuild.
> I am using VS2019 16.4.2, Windows App Certification Kit 10.0.0.18362.1
> If I install the package by myself everything is working fine, but I need to run the Certification Kit to verify if I do not use wrong api because of using also c++ code in the app.
> 
> Was there a solution found for this?
> 
> ![image](https://user-images.githubusercontent.com/4369528/72107411-8b32d580-3331-11ea-95d7-c9f84cbbe4dd.png)

According to #1747 this issue was fixed with an update to VS, but it looks like you are one a pretty new version yourself. @michael-hawker Can you confirm the version of VS that the fix is included in? Is it possible this has regressed again?

**Comment by michael-hawker** [comment]
@StephenLPeters I don't work on VS, I was just being a messenger from what I had heard on the other thread.  I believe it's in the Preview though not the 16.4.x.  I just updated an app in the store the other week with the latest WinUI though, so it shouldn't block submissions.

@LyalinDotCom do you know who owns this part of VS and could comment?

**Comment by jevansaks** [comment]
Are you blocked from running the Certification Test locally only? Or is this also blocking your store submissions?

There was at least one issue with the WACK test in the 1903 Windows SDK which was patched in a version of the WACK that went to the store but isn't available in any officially released Windows SDK. The fixed version is available in insider SDKs though.

**Comment by ThE-TiGeR** [comment]
I did not try to submit it until know. I just wanted to test if the app is still compliant because I did a lot of changes in the past

**Comment by matthewacme** [comment]
I can report I currently am having the same exact problem. I also cleaned my project, deleted all bin and obj folders, completely rebuilt from scratch and I am using VS2019 16.4.2, Windows App Certification Kit 10.0.0.18362.1

![image](https://user-images.githubusercontent.com/11168104/72286530-52d21680-3613-11ea-9f62-176e79ab518f.png)

**Comment by michael-hawker** [comment]
❗ Calling this out as important from @jevansaks (maybe we can edit the initial post at put it at the top of the issue)

> There was at least one issue with the WACK test in the 1903 [18362] Windows SDK which was patched in a version of the WACK that went to the store but isn't available in any officially released Windows SDK. The fixed version is available in insider SDKs though.

@jevansaks to clarify, if they pull just any [preview SDK](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) **newer** than 18362 on an insider build that should resolve the issue?

**Comment by jevansaks** [comment]
> ❗ Calling this out as important from @jevansaks (maybe we can edit the initial post at put it at the top of the issue)
> 
> > There was at least one issue with the WACK test in the 1903 [18362] Windows SDK which was patched in a version of the WACK that went to the store but isn't available in any officially released Windows SDK. The fixed version is available in insider SDKs though.
> 
> @jevansaks to clarify, if they pull just any [preview SDK](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) **newer** than 18362 on an insider build that should resolve the issue?

That's my understanding, but I haven't heard anyone who ran into this problem confirm it does resolve it. If it doesn't then we need to loop in SDK folks again.

**Comment by sibille** [comment]
We ran into this problem on one of our build servers executing WACK tests for Windows Template Studio. I tried to install a preview SDK (10.0.19546.1000) but could not, as the SKD is not compatible with the machine (Windows 10 Version 1909).

**Comment by vigouredelaruse** [comment]
i find i can reliably fix this issue with a commit that looks as per the attached image - the issue is still current to the WACK insider windows 10 sdk/build 

![image](https://user-images.githubusercontent.com/31052867/74559025-6c77be00-4f31-11ea-8fc5-e09a696aa6e9.png)

**Comment by ThE-TiGeR** [comment]
This issue still happens with the version 2.4

![image](https://user-images.githubusercontent.com/4369528/82838336-3650bf80-9ecc-11ea-872f-3151a0b0aeb3.png)

**Comment by ThE-TiGeR** [comment]
I updated to VS2019 16.6.0 and SDK 10.0.19041.0, it still has this issue with the App Certification Kit 10.0.19041.0

**Comment by mobiletonster** [comment]
I'm seeing the same issue with my WACK

![image](https://user-images.githubusercontent.com/3613397/83352739-fc881a80-a30a-11ea-8ba3-c542ab306811.png)

**Comment by ranjeshj** [comment]
@jevansaks Looks like we are hitting this issue again. Can you loop in the SDK folks who can help ?

**Comment by StephenLPeters** [comment]
@jevansaks and @ranjeshj where did we land on this?

**Comment by ranjeshj** [comment]
From earlier in the thread it looks like there was an issue in WACK that was fixed after 18362. @ThE-TiGeR you mentioned that you used a newer version (19041) but still hit the issue. Are you seeing this with a blank app ?  Is there a repro you could share ?

**Comment by scout208** [comment]
I can confirm that installing the latest prerelease version of Microsoft.UI.Xaml (v2.5.0-prerelease.200923002) fixes this issue. So, I'm guessing that this will be resolved in the next general release of Microsoft.UI.Xaml?

**Comment by michael-hawker** [comment]
@scout208 the pre-release builds are built differently than the main releases, so a test with a build from their main pipeline should be done.

**Comment by scout208** [comment]
@michael-hawker Yeah, that's what I started with and that one doesn't work.

**Comment by LucaZiegler** [comment]
Same issue with Xamarin Forms (UWP)

**Comment by tualatin** [comment]
Same here, current Visual Studio 2022 version, latest nuget packages.

**Comment by bpulliam** [comment]
The original issue was with WinUI 2 and VS 2019. If you see this issue now, please open a new issue so we can track it correctly.
