### ISSUE TITLE
Proposal: Make TreeView.SelectedItem a DependencyProperty

### ISSUE THREAD

**Issue by quinmars** [microsoft/microsoft-ui-xaml#2458]
# Proposal: Make `TreeView.SelectedItem` a `DependencyProperty`

## Summary
The TreeView.SelectedItem property is not a DP, hence it is not possible to bind to the view model with the `TwoWay` mode.

## Rationale
One common pattern for a list or tree view is the master detail pattern. The user selects an item from an items view (`ListView`, `ComboBox`, `ListBox`, `TreeView` etc.) and in a secondary view more details for the given item are presented, for example the body of an email, the content of a directory or the article of an rss feed. In order for the view model to retrieve the selected email from the server, it must know if and which email was selected in the list/tree.
In most, if not all, other items controls, the `SelectedItem` property is infact a `DependencyProperty`.

**Comment by MartinZikmund** [comment]
I am all for this proposal, I spent quite a few minutes trying to understand why my binding was not working until I found out it is not in fact a dependency property 😀

**Comment by chingucoding** [comment]
Yes, this should definitely be a DP in my opinion.
If this proposal get's accepted, I think it would be pretty straightforward to implement.

**Comment by dpaulino** [comment]
Yes please

**Comment by ranjeshj** [comment]
@MikeHillberg graciously offered to do the spec work for this. Thanks!  @dpaulino/@chingucoding, would one of you be able to create a PR ?

**Comment by chingucoding** [comment]
If @dpaulino does not want to create a PR I would step in, but I'll leave it up to @dpaulino to decide :)

**Comment by dpaulino** [comment]
@chingucoding unfortunately don't have bandwidth this week. Please feel free to take this Marcel

**Comment by chingucoding** [comment]
Right, will do. Thanks.

**Comment by chingucoding** [comment]
While we are at it, should `SelectedNode` also become a DP?

**Comment by ranjeshj** [comment]
SelectedItem is definitely useful as a dependency property so that it can be bound. I'm not sure if there is much use making SelectedNode a dependency property.  I might be wrong.

**Comment by quinmars** [comment]
I really like your open source spirit. I had a similar issue with WPF a few years ago. But I would never have thought of reporting this. I would not have even known where. And here it was solved in less than two weeks. Thank you very much!

**Comment by sis2004** [comment]
As I reported under [another issue](https://github.com/MicrosoftDocs/winui-api/issues/31#issuecomment-742857849), I tried to upgrade to the recent stable release 2.5.0, and discovered that `TreeView.SelectedItem` is still not recognized as a dependency property there, apparently due to the fact that it was never moved out of preview.

@ranjeshj, @StephenLPeters and @MikeHillberg - can you tell why it's still in preview and when it might get moved out of preview?

This is critical for us, since we'd be stuck with using a pre-release version, which has its own set of issues.

**Comment by StephenLPeters** [comment]
I'm not sure why it wasn't included in the 2.5 release. I'll talk to the team, maybe we can include this in a later patch to the 2.5 release. No promises though.

**Comment by ranjeshj** [comment]
The spec is already updated. @chingucoding can you move this API out of preview ?

**Comment by chingucoding** [comment]
Sure, I'll create a PR shortly.
