### ISSUE TITLE
Unable to drop files onto Grid in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2715]
**Describe the bug**

We able to drag and drop files onto a Grid in our UWP application. 

However, once we switched over to WinUI3 Desktop, we are no longer able to drag and drop files.

**Steps to reproduce the bug**
1. Clone the [WinUI3 Problems DragDropFile repository](https://github.com/eleanorleffler/WinUI3_Problems_DragDropFile).
2. Go to the DragDropFileWinUI folder.
2. Open the DragDropFileWinUI solution in Visual Studio 2019 Preview.
3. Build and run with Debug x64.
4. Attempt to drag a local file onto the application.
5. You should see the "not permitted" symbol (circle with slash) as you are dragging over.

**Expected behavior**

We expect to see the drag indicator change to "Open" or "Add" and be able to drop files onto the Grid. 

This application does not open the file. It only displays the file name to verify the drop event.

We expect to see the same behavior we saw in UWP. 

Build and run the DragDropFileUWP solution inside the DragDropFileUWP folder to see expected behavior.

**Screenshots**

![DragDropFileExpectedBehavior](https://user-images.githubusercontent.com/9272634/85139581-3bbed280-b20a-11ea-968b-a638daf416c2.PNG)

Screenshot#1 - Sample Application Appearance

**Version Info**

NuGet package version:

[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:

Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Additional context**

When we debugged the solution, we noticed that the grid_DragOver does not get called when we put a break point on Line 42 in MainPage.xaml.cs.

**Comment by StephenLPeters** [comment]
@MikeHillberg @JesseCol @llongley is this a known issue with the preview?

**Comment by DierkDroth** [comment]
This issue is getting in our way quite significantly, in particular in the scenario mentioned in #3106 

Is there any ETA on when this problem would be fixed/addressed? May be with next preview?!?

**Comment by StephenLPeters** [comment]
@Austin-Lamb or @MikeHillberg ?

**Comment by jevansaks** [comment]
I've fixed an issue blocking drag&drop in WinUI3 so this works for some cases but I'll leave this open as there's one last problem with accepting files in a drop operation and that is that the "DataView" property isn't working in .NET 5 due to a Cs/WinRT issue. @Scottj1s is going to look into that and then this scenario should work for all cases.

**Comment by DierkDroth** [comment]
Thanks. Appreciate the continued work on that issue...

**Comment by DierkDroth** [comment]
Hi, is there any update available on that issue? Could we expect to see it addressed with next WinUI 3 preview?

**Comment by wbokkers** [comment]
Is see the following exception in the DragOver event handler, when I want to access the DataView property:

System.InvalidCastException: Unable to cast object of type 'Windows.ApplicationModel.DataTransfer.DataPackage' to type 'Windows.ApplicationModel.DataTransfer.DataPackageView'.
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at Windows.ApplicationModel.DataTransfer.DataPackageView.FromAbi(IntPtr thisPtr)
   at ABI.Microsoft.UI.Xaml.IDragEventArgs.global::Microsoft.UI.Xaml.IDragEventArgs.get_DataView()
   at Microsoft.UI.Xaml.DragEventArgs.get_DataView()

This happens in WinUI 3 Preview 3. 
Sometimes I'm in luck and the typecast to DataPackageView is not tried. Maybe one in twenty tries.

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by wbokkers** [comment]
@anawishnoff / @marb2000  This issue was kept open due to the DataView property not working. See @jevansaks comment: https://github.com/microsoft/microsoft-ui-xaml/issues/2715#issuecomment-691338224

Is still have this issue with Preview 4. 

![image](https://user-images.githubusercontent.com/4835617/108690160-4f89a980-74fa-11eb-90cc-981cdcd4816f.png)

**Comment by JesseCol** [comment]
Thanks

**Comment by JesseCol** [comment]
Thanks @wbokkers  -- my apologies, I tried this on Preview 4 and I thought it was fixed.  We'll take another look.

**Comment by jevansaks** [comment]
This wasn't a WinUI bug but actually a Cs/WinRT issue. @Scottj1s did the projection stop using GetRuntimeClassName to identify projection types? (At least when the metadata clearly specifes a type)?

**Comment by wbokkers** [comment]
This is still not solved in Reunion 0.5

**Comment by wbokkers** [comment]
Setting the bitmap does not work either in Reunion 0.5.
args.DragUI.SetContentFromSoftwareBitmap( ... ) does not show the bitmap.

**Comment by wbokkers** [comment]
This is still not solved in Reunion 0.5

**Comment by marb2000** [comment]
@wbokkers, was is exactly your scenario?  I have the @eleanorleffler sample working on Reunion 0.5.

[DragDropFileWinUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6231339/DragDropFileWinUI.zip)

Is there a repro I can take a look at?

**Comment by wbokkers** [comment]
My scenario's:
* Drag/Drop *from within* the app itself, using DataView properties.
* Setting the bitmap of the DrahUI

I changed your code to add these scenario's
[DragDropFileWinUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6231579/DragDropFileWinUI.zip)

**Comment by Marv51** [comment]
Same issue here as @wbokkers, even with newest CSWinRT from April .net update that fixed quite a few other issues.

 Is there any additional info that is needed to fix this? Maybe @anawishnoff can help channel to the right people?

**Comment by marb2000** [comment]
It still can repro this in Reunion 0.5.5. It seems to me a C#/WinRT projection bug. I opened a bug in the C#/WinRT site: 

https://github.com/microsoft/CsWinRT/issues/807

@Scottj1s , @angelazhangmsft,  @AdamBraden, and @manodasanW  for awareness.

**Comment by rick-de-water** [comment]
Just ran into this. Implementing drag and drop is pretty much impossible without access to `DataView`. Any idea when this will be fixed?

**Comment by rick-palmsens** [comment]
Just ran into this. Implementing drag and drop is pretty much impossible without access to DataView. Any idea when this will be fixed?

**Comment by Marv51** [comment]
It's scheduled for CsWinRT 1.2.7, which should be the next update sometime in late June (according to the bug @marb2000 linked above)

That being said, drag and drop within the app kind of works, you just cannot use the DataView. I store the data I would like to pass via DataView now in a separate class every time a drag starts, so when a drop occurs, I can just get it from there.

**Comment by angelazhangmsft** [comment]
cc/ @j0shuams, who is looking into this bug.

**Comment by Marv51** [comment]
@j0shuams can you reproduce the issue? Let us know if anymore info is needed or might help!

**Comment by j0shuams** [comment]
@Marv51 Hi, yes I can reproduce and have some basic investigation into the issue done. Planning on having it fixed by middle of next week.

**Comment by rick-palmsens** [comment]
That is good to hear. When that is done, do I need to wait for an update for WinUI as well, or can I force it to use a newer version of CsWinRT?

**Comment by Marv51** [comment]
@rick-palmsens Update of CsWinRT is possible, see my issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/4571

**Comment by bkudiess** [comment]
I've just tested this with @wbokkers repro app in WindowsAppSDK 1.0 experimental and it seems to work. 

Closing this issue, please let me know if it persists on your tests and I can reopen again.

**Comment by nzhome** [comment]
I am still seeing this issue in 2025 with latest WinUI packs. this is nearly making me want to leave windows altogether and go work for Apple.  I can't believe we can't drag and drop in 2025. absolutely ridiculous.
