### ISSUE TITLE
Application hangs on GC.Collect()

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3437]
**Describe the bug**
Some of our components use DirectX to fast render. On porting I found an issue that application hangs when I put such components in window`s content. After some researching I suggest that the issue relates to GC and interrop services. I prepared a synthetic sample to reproduce this issue. In my sample I create a descendant of SurfaceImageSource. After initialize component I query ISurfaceImageSourceNative interface from SurfaceImageSource.

![image](https://user-images.githubusercontent.com/23479280/96266512-6578e200-0fcf-11eb-938d-42f2a0db82cb.png)

![image](https://user-images.githubusercontent.com/23479280/96266620-85a8a100-0fcf-11eb-8e27-7dd9ebc32e3f.png)

![image](https://user-images.githubusercontent.com/23479280/96266679-96591700-0fcf-11eb-8ae2-057cb2e99392.png)

On Window SizeChanged event I call GC.Collect(). When I run app and start resizing, the application hangs. If I run app under visual studio debugger, the application hangs with Visual Studio together.

If I comment GC.Collect (ln 43) or comment Marshal.GetObjectForIUnknown(pOut) line (ln 38), all works fine. There is why I suggested that issue relates to garbage collector and interrop services.

**Steps to reproduce the bug**
1. Compile and run attached project
2. Resize a window. Application will hang.
3. Comment line 43 (GC.Collect()) and run application again. All will work without errors.
4. Uncomment line 43 and comment lines 38-40. All will work good again.

[App31.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5392119/App31.zip)

**Version Info**

Windows 10 1903 (OS Build 18362.1082)

**NuGet package version:**

WinUI 3.0.0-preview2.200713.0

**Windows app type:**

| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@codendone thoughts no this?

**Comment by alexserov** [comment]
After looking into the @BorzillaR sample, I see that the issue reproduces when the `coreclr!RCWWalker::s_pGCManager` field is not null. So I can hardly imagine how to work with native (COM) Windows runtime types since this may lead to application hanging.

To reproduce this, you can create a blank app from the Visual Studio template and replace the MainWindow ctor with the following code:
```csharp
public MainWindow() {
    this.InitializeComponent();
    try {
        Marshal.GetObjectForIUnknown(ThisPtr);
    } catch { }
    GC.Collect();
}                
```

If you attach a debugger to the application, you'll see a deadlock with the following call stack:
```
[0x0]   ntdll!NtWaitForAlertByThreadId + 0xc   
[0x1]   ntdll!RtlAcquireSRWLockExclusive + 0x17b   
[0x2]   Microsoft_UI_Xaml!DirectUI::ReferenceTrackerManager::ReferenceTrackingStarted + 0x3a   
[0x3]   coreclr!TrackerObjectManager::BeginReferenceTracking + 0x39   
[0x4]   coreclr!InteropLib::Com::BeginExternalObjectReferenceTracking + 0xb   
[0x5]   coreclr!Interop::OnGCStarted + 0x84   
[0x6]   coreclr!GCToEEInterface::GcStartWork + 0x31   
[0x7]   coreclr!WKS::gc_heap::garbage_collect + 0x23b   
[0x8]   coreclr!WKS::GCHeap::GarbageCollectGeneration + 0x1b0   
[0x9]   coreclr!WKS::GCHeap::GarbageCollectTry + 0x52   
[0xa]   coreclr!WKS::GCHeap::GarbageCollect + 0xc9   
[0xb]   coreclr!GCInterface::Collect + 0x56   
[0xc]   System_Private_CoreLib!System.GC.Collect()$##60003C0 + 0x23   
```

**Comment by Austin-Lamb** [comment]
I think Marshal.GetIUnknownForObject and other Marshal helpers may not be correct to use with C#/WinRT's projections.  @stevenbrix or @Scottj1s do you know if that may be what's going on?  Is it a CLR bug?

**Comment by alexserov** [comment]
@Austin-Lamb, by the way, as far as I know, the code from the original sample works fine both for UWP and WinUI for UWP platforms.

**Comment by Maoni0** [comment]
@alexserov you mentioned it's a deadlock, can you please show the stack that holds the lock this thread wants? 

in any case though, this is not a GC issue - xaml just takes the opportunity when a GC is triggered and do their reference walk.

**Comment by stevenbrix** [comment]
I just tested this out with our preview3, and it doesn't look like this will be an issue anymore. But yes, the usage patterns are now changing. With Preview3, the code in the example should just look like this:

```csharp
var imageSource = new MyImageSource();
var nativeInterface = imageSource.As<ISurfaceImageSourceNative>();
```

@angelazhangmsft, is this documented anywhere in the cswinrt repo?

See https://github.com/microsoft/CsWinRT/issues/561

**Comment by angelazhangmsft** [comment]
@stevenbrix No, should this be documented as a breaking change in v1.0 of cswinrt?

**Comment by alexserov** [comment]
@Maoni0 I don't see any other callstacks related to the lock, however, I might have missed something due to the lack of experience in such cases… From my side, it looks like there are several AcquireSRWLockExclusive calls without calling the ReleaseSRWLockExclusive on the same thread. Anyway, it seems that the issue is already resolved in the Preview3, according to the https://github.com/microsoft/microsoft-ui-xaml/issues/3437#issuecomment-721377750

**Comment by BorzillaR** [comment]
@stevenbrix, I have changed my code according to your recommendations

![image](https://user-images.githubusercontent.com/23479280/98245231-ac7c4680-1f81-11eb-9ff7-a23b6bd7d227.png)

Nothing was changed. It still hangs.

**Comment by stevenbrix** [comment]
> No, should this be documented as a breaking change in v1.0 of cswinrt?

@angelazhangmsft, yeah we should document the new way to interop with COM when using cswinrt. I would follow up with Scott, I think he's started on some documentation for this.

**Comment by stevenbrix** [comment]
@BorzillaR, yeah I think you would need to be using a more recent version of the .NET5 runtime to validate this with preview2 bits. 

Our Preview3 release is coming out soon, so this should be addressed by then, where you can use .NET5 GA

**Comment by angelazhangmsft** [comment]
@stevenbrix Scott has added this [COM interop guide](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md) to the CsWinRT repo

**Comment by stevenbrix** [comment]
Great, thanks @angelazhangmsft!

I'm going to close out this issue now that preview3 has been released. @BorzillaR, if you see this issue again, please respond and I will re-open. Thanks!
