### ISSUE TITLE
CommandBarFlyout content extends beyond the taskbar

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#4881]
**Describe the bug**

CommandBarFlyout secondary commands content extends below the taskbar, which cuts off the commands. It does seem to recognize the bounds of the window itself (and will adapt when the content would extend below the window), just not the taskbar. This occurs when the taskbar is in bottom and left positions, it does not occur when the taskbar is in top or right positions. 

**Steps to reproduce the bug**

1. Open xaml controls gallery (with winui 2.6 preview), navigate to CommandBarFlyout page
2. Drag window towards bottom of display
3. Right click image
4. Content extends below taskbar

**Expected behavior**
The CommandBarFlyout should move if it is at the bounds of the window.

**Screenshots**
In Xaml controls gallery with Microsoft.UI.Xaml 2.6.0-prerelease.210405001:
![image](https://user-images.githubusercontent.com/59544401/115762282-277ec100-a358-11eb-8e64-e9f88e209f87.png)

In an actual app (Files) with Microsoft.UI.Xaml 2.6.0-prerelease.210405001:
![image](https://user-images.githubusercontent.com/59544401/115762080-ebe3f700-a357-11eb-9aba-9f26eb380d66.png)

Left taskbar position:
![image](https://user-images.githubusercontent.com/59544401/115765038-1d11f680-a35b-11eb-9f3c-31d59a49469a.png)

This doesn't seem to occur when the taskbar is set to right position:
![image](https://user-images.githubusercontent.com/59544401/115764965-066b9f80-a35b-11eb-9def-b738c7f27f14.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0-prerelease.210405001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19043.962)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Wow, for some reason our Bot never tagged this with Needs-Triage so we haven't seen it... Thank you for reporting @winston-de .

**Comment by StephenLPeters** [comment]
I beleive this issue has been fixed. @ranjeshj and @llongley FYI

**Comment by ranjeshj** [comment]
@winston-de does this still repro with latest bits ? We have made some fixes in this area in windows 11, so you might not see this fix in windows 10 unfortunately.

**Comment by winston-de** [comment]
No, this doesn't repo in 22000.71. Thanks for the fix!

**Comment by winston-de** [comment]
Looks like this issue still seems to occur (build 22000.184) with the left and right sides of the screen...

![image](https://user-images.githubusercontent.com/59544401/132905705-faab55eb-fe88-4796-b5f9-1ae77fdada9b.png)

**Comment by yaira2** [comment]
Was this resolved?

**Comment by DmitriyKomin** [comment]
@winston-de, thank you for reporting this. Unfortunately we are currently unable to investigate WinUi2 issues (more on that [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2), but I tested this on WinUI3 Gallery and am not able to repro in the scenario of your screenshot #1: 

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/45051803/9f030ef4-d917-44ac-872d-5082f1f8d00f)

- the flyout is positioned above the taskbar as expected when invoked near the task bar area. I suspect a fix was made in WinUI2 as suggested in earlier comments (and has been ported to WinAppSDK). 

Resolving in light of the above. Please comment here if you still repro the problem in WinAppSDK.
