### ISSUE TITLE
Often ThemeShadow breaks and appears on top of elements

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#5133]
**Describe the bug**

It seems that in classic UWP apps `ThemeShadow` often breaks, appearing on top of elements using it, such as `MenuFlyouts` and other popups.
Unfortunately I don't have a pattern to reproduce this issue, but as a user I get this state multiple times per week.
Sometimes it is enough to restart the affected app, other times it happens system wide and you have to reboot the whole PC.

**Expected behavior**

Shadow appears below the context menu and not on top.

**Screenshots**

![image](https://user-images.githubusercontent.com/8152849/120501716-206cb900-c3c2-11eb-8395-4ab400a28b14.png)

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
@FrayxRulez more details on when this happens/repro steps would be useful. Are you saying restarting fixes the issue ? That makes me wonder if this is a rendering issue.

**Comment by FrayxRulez** [comment]
Unfortunately I don’t have any repro steps at the moment, maybe @makisukurisu does, as it seems to happen way more frequently to him than to me. 

In most circumstances relaunching the app app is enough, but sometimes a whole OS restart is required, yes.

**Comment by mdtauk** [comment]
> @FrayxRulez more details on when this happens/repro steps would be useful. Are you saying restarting fixes the issue ? That makes me wonder if this is a rendering issue.

This is a known issue, its been brought up many times before.

Supposedly the base popup was adjusted to fix this, or it was said to be investigated.

**Comment by roxk** [comment]
Using ambie, it is very easy to reproduce. Is there any known work around for this issue?

https://user-images.githubusercontent.com/16918354/120662975-2ba40f80-c4bc-11eb-9d67-2846fdfb329b.mp4

cc @dpaulino

**Comment by dpaulino** [comment]
Yes this happens super often. I never found a specific set of reproduction steps though. In general, just open the fly outs repeatedly, and at some point that bug appears. Really annoying.

**Comment by mdtauk** [comment]
It seems to happen a lot in the MUXTestApp when using the CommandBarFlyout test pages

**Comment by winston-de** [comment]
I've had this issue quite a bit as well, affecting most all uwp apps I use. Unfortunately, I also can never consistently reproduce it.
One thing I've noticed is that once it starts happening in one app, it happens in all of them.
Another thing I've noticed is that a lot of times the issue will occur only in certain parts of the display. For example, if I'm having this issue with an app that is on the left side of the screen, many times I can drag the app to the right side of the display, invoke the same menu, and the issue will not occur. I will make some screen recordings when I get the chance.

Usually, it is only fixed by restarting Windows, but sometimes it will fix itself seemingly randomly.

**Comment by codendone** [comment]
Next time you hit this, can you try restarting explorer.exe to see if that fixes the issue?

**Comment by dpaulino** [comment]
@ranjeshj I think I just discovered consistent reproduction steps.
1. Clone Ambie White Noise https://github.com/jenius-apps/ambie
2. Run the app. It's a uwp app.
3. Click the timer button at the top right corner (green arrow on the left in the screenshot)
4. Then click the `...` button near it (orange arrow on the right in the screenshot)
![image](https://user-images.githubusercontent.com/7649589/120881783-6f644b00-c588-11eb-92bf-5f762547e0a9.png)
5. Observe the `...` context menu has the broken shadow bug.

Here's another gif showing the bug. You can see that the first time I open `...`, the bug isn't present. But after I open the timer menu, the bug is present.

![brokenshadow](https://user-images.githubusercontent.com/7649589/120881853-e7327580-c588-11eb-89c4-60a460879a38.gif)

These steps reproduce in Ambie's main branch and in the production release from the store.

**Comment by dpaulino** [comment]
@codendone Restarting explorer.exe doesn't fix the issue for me.

**Comment by dpaulino** [comment]
Ping. Can I provide more information for this?

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/124739044-16535280-df4c-11eb-8461-00f0bd75b0eb.png)

**Comment by FrayxRulez** [comment]
@HppZ not he same issue: #5277

**Comment by Poopooracoocoo** [comment]
@StephenLPeters was this fixed by WinUI 2.6.1?

**Comment by zadjii-msft** [comment]
This might be MSFT:33411893, though that might be Win11+ only builds.

**Comment by Poopooracoocoo** [comment]
Now that XAML Controls Gallery 1.2.20.0 uses WinUI 2.6.1, I can confirm that this was NOT fixed.

**Comment by StephenLPeters** [comment]
@Poopooracoocoo I haven't been able to reproduce this in XCG, can you confirm the steps you are taking to see the issue?

**Comment by Poopooracoocoo** [comment]
@StephenLPeters on W10 v20H1, I went to the CommandBarFlyout sample and right clicked on the image.

**Comment by codendone** [comment]
Tracked internally as [MSFT:34857240](https://dev.azure.com/microsoft/OS/_workitems/edit/34857240).

**Comment by Userlinger** [comment]
Does anyone know a way to deativate the shadows? This issue creates terrible usability. I looks like the items are greyed out and thus misleads the user to assume the option is not available.

**Comment by zadjii-msft** [comment]
FWIW it looks like [MSFT:34857240](https://dev.azure.com/microsoft/OS/_workitems/edit/34857240) was fixed sometime around Windows build 22445. MSFT:33411893 got duped to MSFT:34432192, and that looks like it's fixed in all Windows 11 builds? So this might just be fixed OS-side.
