### ISSUE TITLE
Unhandled exception after upgrade from reunion 0.8 preview to 0.8

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#5295]
**Describe the bug**
This bug occurs after upgrading from Preject Reunion 0.8.0 preview to Reunion 0.8.0
![image](https://user-images.githubusercontent.com/16069721/123522439-8a286c00-d6bd-11eb-9a09-29c492130790.png)

**Steps to reproduce the bug**
Upgrade from Reunion 0.8.0 preview to 0.8.0

**Expected behavior**
It should work

NuGet package version: 
[WinUI 3 - Project Reunion 0.8] 

Windows app type:
Packaged app 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21390)              |  Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Packages in unpackaged app
![image](https://user-images.githubusercontent.com/16069721/123522514-f99e5b80-d6bd-11eb-9666-7108ea1ceefd.png)

**Comment by JanRajnoha** [comment]
Output window:
![image](https://user-images.githubusercontent.com/16069721/123522788-e7bdb800-d6bf-11eb-944f-594e757182cf.png)

**Comment by asklar** [comment]
@JanRajnoha are you launching the app package project, or the app project? (should launch the package)

**Comment by asklar** [comment]
There looks to be an issue with running on Insider builds, I can repro this too.
Internal tracking - https://task.ms/34005792

**Comment by JanRajnoha** [comment]
@asklar It is packaged app, that's why shocked me. I did all steps from docs to upgrade to stable from preview, so I have no idea where is problem.

**Comment by JanRajnoha** [comment]
My first thoughts were it is caused by NuGet packages, but with it I'm not sure. I tried remove acrylic brush from app, where is used in Xaml code, but it didn't help.

**Comment by asklar** [comment]
if you upload a crash dump somewhere I can take a look to see if it is the same issue I referred to above (in VS go to the Debug menu -> save dump as)

**Comment by manodasanW** [comment]
@JanRajnoha I believe this is the same issue I ran into when I was using the sample app that you provided for another issue.  I believe Microsoft.Toolkit.Uwp.UI.Controls has references to AcrylicBackgroundSource, but that type has been [removed](https://github.com/microsoft/microsoft-ui-xaml/issues/5260) in 0.8.  Can you try replacing your reference to Microsoft.Toolkit.Uwp.UI.Controls with a reference to CommunityToolkit.WinUI.UI.Controls version 7.0.3 (note that I believe the package [rebranded](https://devblogs.microsoft.com/ifdef-windows/windows-community-toolkit-for-project-reunion-0-5/#package-identity-and-renaming)).  I think that should resolve the issue you are seeing.

**Comment by JanRajnoha** [comment]
@manodasanW I knew about removing, but have to miss some information or correctly link them. Anyway, after changing package, app will launch and it looks like, it is working okay. So I'm closing issue.

**Comment by martibravo** [comment]
@JanRajnoha Do not close it yet. My app has CommunityToolkit.WinUI.UI.Controls 7.0.3 and still has this issue.

**Comment by JanRajnoha** [comment]
@martibravo I will test Windows 11 in next few hours, so I reopen it.

**Comment by martibravo** [comment]
It looks like Issue #3954 hasn't been solved yes. @riverar's [comment ](https://github.com/microsoft/microsoft-ui-xaml/issues/3954#issuecomment-767071036) from January still happens on Insider builds. Debbugging the exception and loading symbols on W11 and the latest VS Preview shows that Microsoft.Internal.FrameworkUdk.dll crashes when calling GetPlatformFunctions() when the app launches. But his [workaround ](https://github.com/microsoft/microsoft-ui-xaml/issues/3954#issuecomment-766507593) doesn't work because the UDK's .dll has been changed and the hex codes he mentions are not the ones that pop up when I go to the address he says.

**Comment by asklar** [comment]
@martibravo yes, that is a known issue (tracked internally as https://task.ms/34005792) which will be fixed the next time the SDK ships/is serviced. In the meantime the only workaround would be to run the app on a build older than 21390.

**Comment by riverar** [comment]
@asklar Looking at the internals, it appears it's the same issue as before in `Switcher::GetOSVersion`, that is querying for contract versions that the Udk/Reunion/etc. doesn't even support. This breaks application [forward-compatibility promises the team made](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#:~:text=this%20release%20consists%20of%20the%20stability%20updates%20and%20general%20improvements%20that%20allow%20winui%203%20to%20be%20forward-compatible%20and%20production-ready.).

Is this going to continue being a problem moving forward?

**Comment by riverar** [comment]
For those curious, you can alter `Microsoft.Internal.FrameworkUdk.dll` @ `0xe12d` (change `0xE` to `0xD`) on amd64 targets. I haven't looked at x86/arm64 targets yet but given the way everything is now bundled, getting this workaround into your app will be a challenge.

**Comment by jonwis** [comment]
> Is this going to continue being a problem moving forward? Will developers need to recompile their apps for each minor/major release of the OS? (cc @jonwis)

No - this was a one time error on our part.  We're committed to using the Windows App SDK to help apps target all the versions of Windows we support without asking apps to recompile for new editions.

This is actually a great example of the problems we're trying to make better and why it's hard for developers to write version-agile code that lights up functionality on new OS releases while working on older ones. Apps that land on a new version of the OS and expected `GetVersionEx` to return `<=` 12 but it returned 14 that might break its "feature supported" switch statement. That's effectively what happened here. :)

We'll do better.  Thanks for bringing it to our attention.  Any updates will come out as a ProjectReunion framework package servicing release.

**Comment by riverar** [comment]
@jonwis But this has already happened twice now so I'm a bit skeptical. (Previous instance https://github.com/microsoft/microsoft-ui-xaml/issues/3954).

Will await the new version, thanks.

**Comment by asklar** [comment]
CC @codendone @JesseCol fyi

**Comment by JesseCol** [comment]
@riverar -- I'm sorry about that -- yes it's unfortunately true we've hit this bug twice, we're getting a fix in now that should be more robust.  As @jonwis says, our goal is still certainly to shield app developers from having to worry as much about the particular version of Windows that's running, but we're unfortunately hitting some problems as we get there.

**Comment by ePirat** [comment]
Is there any ETA for when a fixed version will be released? IIUC it is currently basically impossible to use Project Reunion aka Windows App SDK with the Windows 11 Insider Preview due to this bug, which is incredibly unfortunate…

**Comment by LJ-Court** [comment]
@ePirat I agree, I've had to install a stable version of Windows 10 on a separate drive just to always have a way to develop

**Comment by Symbai** [comment]
On such a bug which breaks development, isn't it possible to release a fixed version in some kind of preview/experimental branch right now so developers can at least continue to work until the patch (along with all others) are shipped with next "stable" release? Or even better like the .NET runtime repo which has a daily builds infrastructure, this way devs can use it and the .NET team doesn't have to manually bring up a release themselves. Maybe you can talk to them to know how they are doing this. I'm completely new to WinUI so please excuse me if this is a dumb question.

**Comment by JanRajnoha** [comment]
What is the status of the task?

**Comment by nguyenkien** [comment]
> What is the status of the task?

It's seem they fix it, but doesn't bother to release it.

**Comment by ePirat** [comment]
This should be fixed apparently in the [Windows Apps SDK 0.8.1](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-081) release.

**Comment by asklar** [comment]
Closing as this is fixed in 0.8.1. See https://github.com/microsoft/WindowsAppSDK/discussions/1056 for more details
