### ISSUE TITLE
Hovering over AppBarButton and then quickly going to CommandBarFlyout submenu hides submenu 

### ISSUE THREAD

**Issue by lyahdav** [microsoft/microsoft-ui-xaml#5617]
**Steps to reproduce the bug**
1. Create an app with following XAML:
```
        <Button Content="Button1">
            <Button.Flyout>
                <CommandBarFlyout>
                    <CommandBarFlyout.SecondaryCommands>
                        <AppBarButton Label="AppBarButton1">
                            <AppBarButton.Flyout>
                                <MenuFlyout>
                                    <MenuFlyoutItem Text="Item 1"/>
                                </MenuFlyout>
                            </AppBarButton.Flyout>
                        </AppBarButton>
                        <AppBarButton Label="AppBarButton2">
                        </AppBarButton>
                    </CommandBarFlyout.SecondaryCommands>
                </CommandBarFlyout>
            </Button.Flyout>
        </Button>
```
2. Run the app
3. Click button
4. Hover over the AppBarButton with a submenu.
5. Hover over the other AppBarButton and then quickly hover over the submenu.

**Expected behavior**
I'd expect the submenu to stay open, but instead it closes. It does if you use a MenuFlyout instead of CommandBarFlyout for the top level menu.

**Screenshots**
Here's a video of the bug:

https://user-images.githubusercontent.com/359157/128073649-93be0d03-6814-49f5-897b-c0add0ee9779.mov

Here's a video of the same setup using MenuFlyout instead of CommandBarFlyout, showing that it doesn't have this bug:

https://user-images.githubusercontent.com/359157/128073839-c70d5c8c-e3a8-4f72-9c9a-40847d8560e0.mov

**Version Info**
Windows 10 21H1 / 19043

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
The bug seems to be in `AppBarButton.OnPointerEntered`. It schedules a timer to hide any open submenus. That timer should get cancelled if the user hovers over the submenu.

A workaround is to add a PointerEntered event on the MenuFlyoutItems in the submenu with the following code:
```
      menuItem.PointerEntered(
          [parentButton](auto const& /*sender*/, winrt::Input::PointerRoutedEventArgs const& e) {
            parentButton.OnPointerEntered(e);
          });
```

**Comment by StephenLPeters** [comment]
This has been fixed internally, thanks!

**Comment by lyahdav** [comment]
@StephenLPeters it's fixed in WinUI 2.x or 3.x?

**Comment by StephenLPeters** [comment]
Unfortunately the issue was in code that shipped with the operating system. So the fix will work with any Winui 2.x package that is running on an OS that includes the bug fix. This bug fix will be included in Winui 3 at some point in the future as well.

**Comment by lyahdav** [comment]
Can you say what version of the OS so I can wrap the workaround in a version check?

**Comment by lyahdav** [comment]
@StephenLPeters I confirmed using the XAML Controls Gallery app that this bug still happens on Windows 11 21H2 build 22000.71 and it's fixed in Windows 11 21H2 build 22000.120. Is a fix going into any Windows 10 versions?

**Comment by StephenLPeters** [comment]
No, unfortunately a fix for Windows 10 versions wont be possible.  I would recommend an IsApiContractPresent check like this: https://github.com/microsoft/microsoft-ui-xaml/blob/8b7e40a7e8848b62052e63ad9616f66e2763b4a7/dev/dll/SharedHelpers.cpp#L230 to wrap your work around in.  I believe the UAP version for this is 15..

**Comment by lyahdav** [comment]
Thanks, I just checked and it's UAP version 14.

**Comment by lyahdav** [comment]
For anyone going with my workaround in the OP, I found a bug with it. You have to add a `CommandBarFlyout.Closing` event that calls `appBarButton.Flyout(nullptr)` to clear out the Flyout so that the submenu doesn't end up showing in case the user hovers over a submenu item and then quickly clicks away from the menu to close it. The reason being that this schedules a timer to show the submenu again.

**Comment by lyahdav** [comment]
Since I was wondering, I checked if this issue is fixed in WinUI 2.6.1-prerelease.210709001 and it's not.
