### ISSUE TITLE
Multi-Layer keyboard mappings do not function correctly on the UWP framework since Creators Update

### ISSUE THREAD

**Issue by davidfishlock** [microsoft/microsoft-ui-xaml#588]
Multi-Layer keyboard mappings like neo2 do not work correctly within UWP apps. Characters in the upper layers are inaccessible.

- Run a UWP app with neo2 keyboard layout
- Attempt to enter a '!' character

**Expected behavior**
It is possible to enter a '!' character, or any other character in the higher levels of the mapping

**Version Info**
Any Windows 10 OS version since Creators Update

**Additional context**
Note that this keyboard layout functions correctly in the rest of the OS and win32 apps.

Users have been reporting this issue for a couple of years, see the below links for further info:
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/17209457-multi-layer-keyboard-bug
https://www.reddit.com/r/Windows10/comments/63uy0y/creators_update_with_mouse_and_keyboard_issues/

This issue also seems to have been raised against Edge browser:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16024580/

**Comment by jevansaks** [comment]
I need to track down who owns this area. Following up.

**Comment by jevansaks** [comment]
We've filed an [internal issue](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/21268092) on the team. Thanks for reporting!

**Comment by davidfishlock** [comment]
Thanks @jevansaks, I'm not able to view the internal report but will this item be updated in the event of this issue being resolved?

**Comment by jevansaks** [comment]
Yes we'll circle back and comment here when there's a resolution. Alternatively you can file on Feedback Hub and I can link the issue so you can get status that way.

**Comment by jevansaks** [comment]
The internal issue is marked as fixed now. Thanks for reporting!

**Comment by davidfishlock** [comment]
Will this fix require an SDK/framework target upgrade or an updated OS version? Just wondering how this fix will be released so I can communicate to our users.

**Comment by jevansaks** [comment]
I believe it would just be an OS update.

**Comment by JBenda** [comment]
@jevansaks the neo layer 3 still does not work in UWP Apps (e.g. Mail, Edge).

Is the update already out? And if yes, how we can apply it?

Thank you for your time.

**Comment by jevansaks** [comment]
Presumably it would be in the next Windows release (coming this spring). You could try it on an insider build to see if it's fixed there.

**Comment by JBenda** [comment]
It's works with the insider build. Thank you very much for fixing it. 😄
