### ISSUE TITLE
WinUI3: SwapChainPanel renders in wrong position when display scaling is not 100%

### ISSUE THREAD

**Issue by Loghorn** [microsoft/microsoft-ui-xaml#5888]
**Describe the bug**
When rendering a SwapChainPanel it moves off the side of the window. Look at this screen capture:
![repro](https://user-images.githubusercontent.com/2026182/133433962-c989cca5-e543-48d2-9710-92c7f1084daf.gif)
Please note that this behavior is only seen when the display scaling is not 100%, otherwise the rendering surface is correctly placed in the window.

**Steps to reproduce the bug**
1. Open the attached solution. It consists of a WinUI desktop project and a packaging project [repro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7170032/repro.zip)
2. Start the application
3. Set the display scaling to 100%
4. Try to resize the window; this forces a resize of the SwapChainPanel buffers and a render. You should see the grid always shown in the window without problems
5. Change the display scaling to any value different from 100%
6. Try to resize the window; you'll see the rendering surface being moved off the proper position 

**Expected behavior**
The rendering surface remains in the correct position regardless of the display scaling.

**Screenshots**
See GIF above

**Version Info**

NuGet package version: 
*WinUI 3 - Project Reunion 0.8.3 Preview*: 0.8.3-preview 
*WinUI 3 - Windows App SDK 1.0.0*: 1.0.0-experimental1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (Windows 11 22000.184)              | Yes   |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@codendone and @RBrid FYI

**Comment by RBrid** [comment]
@StephenLPeters, could be related to internal Task 33641110 that Keith addressed in WinUI 3.

**Comment by Loghorn** [comment]
The final release of Windows App SDK 1.0.0 still has this issue. Do you have any idea if and when it will be fixed? Is there something I can do to help with the resolution?

Thank you

**Comment by PierreHenriKT** [comment]
I have a similar issue in my [media player for WinUI 3](https://github.com/KlearTouch/KlearTouch.MediaPlayer/issues/3).

I discovered it after I noticed that, when the display scaling is not 100%, the video in my player was permanently rendered incorrectly. So, I had to call `swapChain.SetMatrixTransform(inverseScale)` to fix that. But I still have this issue, but only when the window is small, and only for every other render.

So, I wonder if `swapChain.SetMatrixTransform(inverseScale)` only gets applied to one of the DirectX buffers, leaving the other one incorrectly scaled...

**Comment by castorix** [comment]
I did some tests with SwapChainPanel + Direct2D (P/Invoke) and I fixed this problem by not using  
ISwapChainPanelNative and replacing CreateSwapChainForComposition by **CreateSwapChainForHwnd**
The rendering still works with _CompositionTarget.Rendering_, also _CompositionScaleChanged_ (without SetMatrixTransform)
and I do the resing (_ResizeBuffers_) in _SizeChanged_ event of the main window instead of the SwapChainPanel

**Comment by alexlozdev** [comment]
> I did some tests with SwapChainPanel + Direct2D (P/Invoke) and I fixed this problem by not using ISwapChainPanelNative and replacing CreateSwapChainForComposition by **CreateSwapChainForHwnd** The rendering still works with _CompositionTarget.Rendering_, also _CompositionScaleChanged_ (without SetMatrixTransform) and I do the resing (_ResizeBuffers_) in _SizeChanged_ event of the main window instead of the SwapChainPanel

Will you provide full code?

**Comment by khoabui1412** [comment]
Any update or fix on this?

**Comment by khoabui1412** [comment]
Instead of using `SetMatrixTransform` of DirectX to scale, I use `ScaleTransform` in xaml to scale since it's smoother when resize. Ex: 
```
<SwapChainPanel Width="{x:Bind OriginVideoWidth, Mode=OneWay}"
                              Height="{x:Bind OriginVideoHeight, Mode=OneWay}"
                              HorizontalAlignment="Center"
                              VerticalAlignment="Center"
                              RenderTransformOrigin="0.5 0.5">
                <SwapChainPanel.RenderTransform>
                    <ScaleTransform ScaleY="{x:Bind ScaleY, Mode=OneWay}"
                                                ScaleX="{x:Bind ScaleX, Mode=OneWay}" />
                </SwapChainPanel.RenderTransform>
</SwapChainPanel>
```
But it also has problem as this topic mentioned even with display scale setting is 100%
