### ISSUE TITLE
XAML Islands - Empty DesktopWindowXamlSource window visible on task bar

### ISSUE THREAD

**Issue by taenri** [microsoft/microsoft-ui-xaml#6490]
### Describe the bug

When running a XAML Islands Win32 Desktop app using Win UI 2.6.1 Preview, a blank window with title DesktopWindowXamlSource appears on the task bar.

When the user opens a valid XAML Islands window, the content for DesktopWindowXamlSource is set and it is attached to an HWND. At this point the 'blank' DesktopWindowXamlSource window disappears. As soon as the user closes the XAML Islands window, however, the blank DesktopWindowXamlSource window reappears.

Also notable: closing this blank window will also cause the entire process to exit.

Our app usually does not show any window until the user explicitly opens one through a systray icon, so most of the time the content for DesktopWindowXamlSource is expected to be empty and its HWND should be invisible to the user.

We have found that this issue only repros in the Windows 10 Insider build 19044.1348.

I have also confirmed that this issue persists in Win UI 2.8.0 Preview.

### Steps to reproduce the bug

I was able to repro the issue using the xaml-islands Playground found in this repo: https://github.com/asklar/xaml-islands/tree/main/Playground

1. Clone the xaml-islands repo above.
2. Comment out lines 172-251 in Playground\WindowsProject1.cpp to ensure that the DesktopWindowXamlSource hwnd content does not get set on startup.
3. Build the Playground solution and launch the executable in Windows 10 build 19044 (I can help validate changes on this build of windows if needed)
4. Observe that an empty DesktopWindowXamlSource window appears in the task bar.

### Expected behavior

When using XAML Islands with WinUI 2X preview, the blank DesktopWindowXamlSource HWND should not be visible at all to the user when it is not actively hosting any content.

### Screenshots

![image](https://user-images.githubusercontent.com/65185234/146569063-ea9bf6fc-7be3-45db-9c69-f91b51ddf778.png)
![image](https://user-images.githubusercontent.com/65185234/146569083-451c2333-41bb-416d-80fd-b948fb8f6f37.png)

### NuGet package versions

Microsoft.UI.Xaml.2.6.1-prerelease.210709001
Microsoft.UI.Xaml.2.7.0-prerelease.210913003
Microsoft.UI.Xaml.2.8.0-prerelease.210927001

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (19044)

**Comment by zadjii-msft** [comment]
Possibly relevant discussion: https://github.com/microsoft/terminal/issues/6507#issuecomment-989799727

**Comment by sylveon** [comment]
This is the fake CoreWindow used for OS XAML compat. What I do is grab the HWND of the window using
```cpp
HWND hwnd;
winrt::check_hresult(winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().as<ICoreWindowInterop>()->get_WindowHandle(&hwnd));
```

Then I can just call `ShowWindow(hwnd, SW_HIDE);`

**Comment by MattTheTechLV** [comment]
I posted this originally under the following issue, but a mod said to instead post here, so I am posting here.
Original Post: https://github.com/microsoft/microsoft-ui-xaml/issues/3698#issuecomment-1414515659

Good Evening, I have submitted this using the "Send Feedback" option in OneDrive, but I just wanted to mention here that I am also experiencing this bug, in case it helps whomever is working on this issue.

I just started experiencing this issue the other day after my OneDrive updated to [23.011.0115.0006].

The one Workaround that worked for me was to go into the System Settings in Windows, Go To System / Multitasking / and set "On the taskbar, show windows that are open on" to "Only the Desktop I am using".  But because I use Virtual Desktops and like my Taskbar Icon's to show up on all Virtual Desktops, I would prefer to find a fix to this bug. I noticed some similarities in terms of my system as others experiencing this issue.

I am running Windows 10 22H2 Enterprise. I run dual monitors. I use the Business Version of One Drive. The Specific Version number of OneDrive is: [23.011.0115.0006]

This issue just started happening a few days ago when My OneDrive updated to this newest version. Shortly after I noticed the OneDrive Icon on my Taskbar that had the "DesktopWindowXamlSource" title, and when I closed it, it closed OneDrive altogether. 

Here are some other system specs in case they happen to be relevant, I doubt they are, but figured I would mention them in case they help with diagnosing the issue.

In One Drive, I sync to an Actual OneDrive Business Account, and to multiple Sharepoint Folders. I am not connected at all to a Non Business OneDrive account.

I have the Insider Builds turned off for Both OneDrive and Windows 10 itself.

System Specs:
Ryzen 9 5900x
64GB Ram 3600Mhz CL16
RTX 3080
Win10 22H2 Enterprise

Hopefully this helps, here are some screenshots of the issue and the version.

![image](https://user-images.githubusercontent.com/61740449/217763318-be49d9e0-3b79-4fd5-a6fc-96436a1bf340.png)

![image](https://user-images.githubusercontent.com/61740449/217763368-333bd6a2-9937-4656-8391-92f0f858a8c8.png)

![image](https://user-images.githubusercontent.com/61740449/217763429-b6a3b6fe-eec3-4a03-bf7a-94e38d3fa518.png)


I edited out Device ID's out of habit.

Thank You for your work!

**Comment by sylveon** [comment]
@MattTheTechLV this issue is for bugs with the XAML Islands API, not end user applications.

**Comment by MattTheTechLV** [comment]
> @MattTheTechLV this issue is for bugs with the XAML Islands API, not end user applications.

Yup sorry, I was directed by a Contributor where I originally posted saying it belonged here, then realized right after I posted it, that it in fact did not belong here, and I had posted in the correct place originally. So I deleted my comment almost right away. Sorry about the confusion.

**Comment by taenri** [comment]
> This is the fake CoreWindow used for OS XAML compat. What I do is grab the HWND of the window using
> 
> ```c++
> HWND hwnd;
> winrt::check_hresult(winrt::Windows::UI::Core::CoreWindow::GetForCurrentThread().as<ICoreWindowInterop>()->get_WindowHandle(&hwnd));
> ```
> 
> Then I can just call `ShowWindow(hwnd, SW_HIDE);`

@sylveon - We are performing similar logic by using EnumThreadWindows to search for window handles created on our main thread with the title of "DesktopWindowXamlSource". Then we are calling `ShowWindow(hwnd, SW_HIDE)` to manually hide it. This seems to work well in our local testing using a virtual machine with the same version of Windows 10 that we know to be affected (build 19044, aka 21H2). On my VM, the issue persists without this manual hiding logic but fixed when our manual hiding logic is applied.

However, many of our users are still reporting this issue despite our best efforts. My understanding is that this bug has been fixed at the OS-level within the CoreWindow object itself in Windows 11 (from within the Windows.UI.Core namespace) but has not been patched for Windows 10. Many users are unwilling or unable to make the upgrade from Win10 to Win11 though. Is there any chance that you have contact with someone who contributes to Windows.UI.Core? I would like to work with them internally on a way to patch this up on Windows 10.

**Comment by mario-beeler** [comment]
Hello @taenri 

I don't get it. Is there now a patch we can use for the problem in Windows 10 22H2? Still have the OneDrive Windows and in the other thread is closed with the reason it is opened here. We need some information.

**Comment by sylveon** [comment]
> @sylveon - We are performing similar logic by using EnumThreadWindows to search for window handles created on our main thread with the title of "DesktopWindowXamlSource". Then we are calling `ShowWindow(hwnd, SW_HIDE)` to manually hide it. This seems to work well in our local testing using a virtual machine with the same version of Windows 10 that we know to be affected (build 19044, aka 21H2). On my VM, the issue persists without this manual hiding logic but fixed when our manual hiding logic is applied.
> 
> However, many of our users are still reporting this issue despite our best efforts. My understanding is that this bug has been fixed at the OS-level within the CoreWindow object itself in Windows 11 (from within the Windows.UI.Core namespace) but has not been patched for Windows 10.

Have you tried using ICoreWindowInterop? I've always found manual window searches to be fragile.

**Comment by JJBrychell** [comment]
Because WinUI2 is in maintenance mode and that the issue has a work around (manually hiding the window using ShowWindow) and that there was a reported fix in later releases of Windows 10, we are closing this bug.

If the issue affects WinUi3, please feel free to reopen this issue.

**Comment by taenri** [comment]
@JJBrychell - Just to clarify, there are still some Windows versions where calling ShowWindow does not work. However, there is still another workaround that I think I should mention for others running into this issue:

Calling ITaskbarList::DeleteTab on the CoreWindow HWND will resolve the issue for good.
https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-deletetab
