### ISSUE TITLE
WinUI 2: CommandBarFlyout crashes in certain configurations due to layout cycle at 125% display scale

### ISSUE THREAD

**Issue by lyahdav** [microsoft/microsoft-ui-xaml#7109]
### Describe the bug

The WinUI 2 CommandBarFlyout crashes in certain configurations due to a layout cycle.

### Steps to reproduce the bug

1. **Set Windows display scale to 125%**
1. Clone https://github.com/lyahdav/microsoft-ui-xaml
2. Go to branch https://github.com/lyahdav/microsoft-ui-xaml/tree/cbf-crash
3. Run the MUXControlsTestApp
4. Go to CommandBarFlyout page > Base CommandBarFlyout Tests
5. Click "Show CommandBarFlyout with no primary commands"
6. Notice the CommandBarFlyout renders incorrectly. Some AppBarButtons don't render their labels and the flyout has a scrollbar incorrectly.
7. Scroll the flyout.
8. Observe app crashes with error "Layout cycle detected.  Layout could not complete."

### Expected behavior

I'd expect:
1. App doesn't crash
2. CommandBarFlyout doesn't render with scrollbar
3. AppBarButton labels render correctly

### Screenshots

Here's a video of the crash:

https://user-images.githubusercontent.com/359157/168663701-24c26fef-c416-487c-8c76-5593ea4da4c3.mov

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

The crash doesn't seem to happen with the system XAML CommandBarFlyout, only the WinUI 2 one. Also if I remove at least one AppBarSeparator from the CommandBarFlyout it resolves the issue.

Here are the changes I made to the example to cause it to crash: https://github.com/lyahdav/microsoft-ui-xaml/commit/6ff5cd56b664a2fca079f33c1a45da590153fd0d

**Comment by stmoy** [comment]
@lyahdav - I heard back from @ranjeshj who mentioned that there have been some layout cycle fixes in 2.8. Can you try out the latest prerelease of WinUI to see if it still repros?

**Comment by lyahdav** [comment]
@stmoy I was able to repro in this repo off a commit from May 11 (using steps detailed above). It looks like the latest 2.8 prerelease was from a month ago, so I'm pretty sure I tested on a newer version of WinUI 2.x. Or am I missing something?

**Comment by stmoy** [comment]
Required a fix in ScrollViewer code, not in CommandBarFlyout -- so issue has been fixed in WinUI3 and System Xaml, serviced down to the initial release of Windows 11.

**Comment by lyahdav** [comment]
For posterity, I have a simple Xaml Islands app with WinUI 2 where I reproduced this as well: https://github.com/lyahdav/XamlPlayground/tree/CommandBarFlyout-WinUI2-crash

**Comment by artemious7** [comment]
I also experienced a layout cycle in UWP 10.0.19041 with package version 2.8 when using `DatePickerFlyout`, `TimePickerFlyout`, `CalendarDatePicker`'s flyout. 

# Repro
It happens when the flyout is displayed outside the XAML root (outside the window) and the mouse pointer is moved quickly from the window to the flyout and back. 

# Workaround
Minimizing the window and restoring it closes the flyout and unfreezes the app.

Setting `ShouldConstrainToRootBounds="False"` on the flyout ensures the it is always displayed within the window, so the bug should not occur.

**Comment by codendone** [comment]
A fix for this issue has just been completed for WinAppSDK 1.5 (same fix as for #6218 and #7696). This had already been partially improved in WinAppSDK and also partially fixed in Windows 11 for system XAML (/WinUI2).
