### ISSUE TITLE
WinUI application closed by 'X' but remains as dormant proc 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#7193]
### Describe the bug

I close the WinUI application by pressing 'X' on the window but remains dormant and must kill it in the Task Manager.

### Steps to reproduce the bug

Create new app and derive ```App : PrismApplication```

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Request the information you need and ll provide.

**Comment by michael-hawker** [comment]
@Sergio0694 this is what you were kind of seeing with ComputeSharp too, eh?

**Comment by Sergio0694** [comment]
Sounds similar, yes. In my case I could narrow this down to specifically when a swap chain was rendering.
If that's not the case, the app closes just fine for me. I've opened an issue tracking that issue here: #7153.

**Comment by marb2000** [comment]
Can you still repro this in 1.1 Stable?

**Comment by sigmarsson** [comment]
Yes, still in 1.1 persist. Click on 'X' and the process becomes a backgrdound proc , which I can wintess in Task Manager. 

It moves from the "Apps" list to the "Background Processes" list. 

![image](https://user-images.githubusercontent.com/43340959/172302272-a7427689-c902-47f6-b876-4b11f14d8d1e.png)

**Comment by sigmarsson** [comment]
@marb2000 feel free to request whatever additional information you may need.

**Comment by sigmarsson** [comment]
@marb2000 still able to reproduce it in version ```1.1.3```
Feel free to request any more specific context.

**Comment by pratikone** [comment]
I am looking at this issue now. Btw, cool shader program. it is fun to investigate 😊

**Comment by Sergio0694** [comment]
@pratikone That's awesome, and thank you! 😄

Also let me know if you need any help with the repro - that branch I shared is a bit out of date, so you might also want to just checkout to main (which is on WASDK 1.2 latest now) and see if the issue still repros there anyway once removing the workaround in `App.xaml.cs` to just force terminate the process. I can also help with that if needed 🙂

**Comment by pratikone** [comment]
@Sergio0694 sure, i will check it out.

**Comment by pratikone** [comment]
@Sergio0694  i have some lead.
I have a workaround (you can also continue the workaround you have).

the bug doesn't appear if your app is self-contained.
if you edit csproj of your app and set
`<WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>`, this problem goes away. I am trying it on `ComputeSharp.SwapChain.WinUI.csproj` in your main [repo](https://github.com/Sergio0694/ComputeSharp).  This is good news. though switching to self contained will increase your package size as everything will be bundled together. 

So, the bug only appears if you are using winappsdk as a runtime rather than a self contained binary. This is an interesting lead. Do you have a swap chain winui sample project which doesn't include compute sharp library ? It will simplify debugging for me. 

(@bpulliam / @gabbybilka   we should add a swapchain sample winui app in [winappsdk samples](https://www.bing.com/search?q=winappsdk+sanmples&cvid=8f4b81e27b9a47b98312fb3d64738db1&aqs=edge..69i57j0l2j69i64j69i11004.6239j0j1&pglt=675&FORM=ANNAB1&PC=U531))

**Comment by Sergio0694** [comment]
That is very interesting, good find! I'm not too concerned about the package size right now since I'm not currently publishing that app in the WinUI 3 version anyway (I'm only publishing the UWP version right now, as it's noticeably faster, consumes less resources, ships as an AOT binary and also has a much smaller package size), but I might as well leave the workaround in there for now to keep things simpler. I hope this discovery will help the investigation though! 😄

> "Do you have a swap chain winui sample project which doesn't include compute sharp library?"

Unfortunately I don't, no 🥲
Getting a full swap chain sample running from scratch is a fair amount of work, and I've had no motivation to try to do that without reusing my library, given those samples are all meant to be a showcase of it. It's certainly possibly to do so (and the code in the library can also be used as a reference, in part), it's just not trivial work and it might require some time 😅

**Comment by castorix** [comment]
> "Do you have a swap chain winui sample project which doesn't include compute sharp library?"

BTW, I had posted a sample with the Media Engine :
[CMediaEngine.cs](https://github.com/castorix/WinUI3_MediaEngine/blob/master/CMediaEngine.cs)
(I have also done others with Direct2D, that I did not upload yet...)

**Comment by pratikone** [comment]
You are right. in successive debugging sessions, the bug reproduced even when the app was self contained. I guess, in earlier times, VS killed the app a few times. Don't know how that happened. Definitely this issue appears whether app is packaged or self contained. 

Also thanks for that media engine link. I will check it out.

**Comment by pratikone** [comment]
@gegao18 can you take a look at this ? it looks like on using swap chain with D3D , memory is being kept alive which is causing the app to not quite during exit. WinUI correctly goes through all its cleanup rountine but the app continues to run. 


easy repro : download https://github.com/Sergio0694/ComputeSharp, run `ComputeSharp.SwapChain.WinUI` sln.

It has the code to forcibly null `ShadeRunner` variable as well as a shutdown timer. You can comment those out for the bug to repo. Appears in both runtime as well as self contained configs.

**Comment by sigmarsson** [comment]
Upon 'X' I witness this :

![image](https://user-images.githubusercontent.com/43340959/218938040-ec747fb8-5b10-47af-8511-2a9dd53a9398.png)

**Comment by sigmarsson** [comment]
Upon 'X' I witness this today , does that help ? 


![image](https://user-images.githubusercontent.com/43340959/226588821-9521e059-ebeb-45ff-84d2-4c47ef971b98.png)

**Comment by pratikone** [comment]
Every piece of debugging information helps. Thanks for doing it. 👍🏾

**Comment by sigmarsson** [comment]
With `1.4` the application deployed, `X` but the proc remains dormant.

**Comment by JesseCol** [comment]
Hi sigmarsson, do you have a minimal repro of this?  Sorry if I missed it somewhere in the thread.  Thanks!

**Comment by michael-hawker** [comment]
> Hi sigmarsson, do you have a minimal repro of this? Sorry if I missed it somewhere in the thread. Thanks!

@JesseCol the other similar issue mentioned had a repro repo here: https://github.com/microsoft/microsoft-ui-xaml/issues/7153#issue-1250217420

Though there wasn't clarity on if it was the exact same issue, it did get closed as a duplicate of this one.

**Comment by JesseCol** [comment]
Thanks!  I built and debugged this project locally: https://github.com/Sergio0694/SwapChainWinUI3Repro

From what I can tell, the CLR is keeping the process alive because there's a managed thread that's still running -- a thread that ComputeSharp had created.

I fixed the sample by doing this:
1. I added an Unloaded handler for ShaderPanel that calls StopRenderLoop().
2. I upgraded the project to WinAppSDK 1.4 (it was on an older version where the Unloaded events weren't always raised correctly).

The Xaml looks like this:
```
<winui:AnimatedComputeShaderPanel x:Name="ShaderPanel" Loaded="AnimatedComputeShaderPanel_Loaded" Unloaded="ShaderPanel_Unloaded" />
```

The C# is like this:
```
    public void StopRenderLoop()
    {
        ShaderPanel.ShaderRunner = null;
    }

    private void ShaderPanel_Unloaded(object sender, RoutedEventArgs e)
    {
        StopRenderLoop();
    }
```

As far as I know this is all by design, so I'm closing this one out.  Feel free to comment and let me know if I missed something.  Thanks!

**Comment by Sergio0694** [comment]
Hey @JesseCol, thank you for looking into this! My `AnimatedComputeShaderPanel` already subscribes to `Unloaded` internally to stop the render thread ([here](https://github.com/Sergio0694/ComputeSharp/blob/e0a5f6e6af528d8f42c099758e333ef017ca3878/src/ComputeSharp.WinUI/Controls/AnimatedComputeShaderPanel.cs#L62-L66)), so I wonder if the issue there wasn't just caused by WinAppSDK using an older version where that event wasn't being raised, and that `StopRenderLoop()` call was not actually the one fixing the issue.

I tried again in my [sample app](https://github.com/Sergio0694/ComputeSharp/tree/main/samples/ComputeSharp.SwapChain.WinUI) (should just be able to F5 deploy it if you open the solution in VS 17.8), and I am not entirely sure about what I'm seeing. When I just run the app normally, I get this (which is fine):

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/10199417/3b15e3a2-d8ed-4a61-8020-ded450e352aa)

Closing the window, the process immediately becomes this:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/10199417/3e111863-b008-4e2a-8a67-ab69811e93bc)

With just the runtime broker being left there, with 0.1 memory use. It seems to then just remain like that for a bit (say, 1-2 minutes), and then it eventually goes away. Is this the expected behavior? The thing is that I'm not entirely sure how this could be explained by eg. the CLR remaining alive because a thread was still running, because if that was the case, then why would the actual process for the app still go away, and the memory use go down to just 0.1 MB? 🤔

**Comment by JesseCol** [comment]
Agreed, if the process app process has exited, it doesn't sound like anything due to the CLR (or WinAppSDK / WinUI).  I'm sorry, I don't have much experience with RuntimeBrokers, so I don't have a good answer to your question.

**Comment by sigmarsson** [comment]
I still experience that the process remains dormant upon 'X' and stays as "Background process" in Task manager. Could either procmon or windbg lend a clue and if so, what specific filter shall I apply to narrow this down ?

**Comment by sigmarsson** [comment]
`(522c.65fc): Windows Runtime Originate Error - code 40080201 (first chance)
(522c.65fc): Windows Runtime Originate Error - code 40080201 (first chance)
(522c.65fc): C++ EH exception - code e06d7363 (first chance)
(522c.65fc): C++ EH exception - code e06d7363 (first chance)
Microsoft.Web.WebView2.Core.dll!00007FFEC3CCCC92: ReturnHr(1) tid(65fc) 8007139F The group or resource is not in the correct state to perform the requested operation.
    Msg:[winrt::hresult_error: The group or resource is not in the correct state to perform the requested operation.] 
(522c.65fc): C++ EH exception - code e06d7363 (first chance)
ModLoad: 00007fff`9bc90000 00007fff`9c0d5000   C:\WINDOWS\SYSTEM32\UIAutomationCore.DLL
ModLoad: 00007fff`d1500000 00007fff`d15a3000   C:\WINDOWS\SYSTEM32\sxs.dll
mincore\com\oleaut32\dispatch\ups.cpp(2126)\OLEAUT32.dll!00007FFFD31E470C: (caller: 00007FFFD31E49FA) ReturnHr(1) tid(65fc) 8002801D Library not registered.
Microsoft.ui.xaml.dll!00007FFEBC06FFEB: 8001010E - RPC_E_WRONG_THREAD
`

... as windbg suggests the `WebView2` isn't gracefully terminated.


```
            Window.Closed += (s, e) =>
            {
                var eventAggregator = Container.Resolve<IEventAggregator>();

                eventAggregator.GetEvent<TerminateEvent>().Publish(new object());
            };
```

`_eventAggregator.GetEvent<TerminateEvent>().Subscribe(OnDispose, ThreadOption.UIThread);`

```
        public void Dispose()
        {
            MyWebView.Close();
        }

        private void OnDispose(object x)
        {
            Dispose();
        }
```

how shall I shutdown it ?

**Comment by sigmarsson** [comment]
May relate to https://github.com/MicrosoftEdge/WebView2Feedback/issues/2398 ?

**Comment by sigmarsson** [comment]
<img width="509" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/43340959/78aacd1f-a55b-4478-ba27-5f0ae71d275b">

however the webview related processes seem to have deceased, only the parent proc remains dormant.

<img width="512" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/43340959/dc2a581a-9463-433f-9a6d-59c934f38dad">

**Comment by JesseCol** [comment]
Hi @sigmarsson -- your scenario doesn't seem to involve RuntimeBroker (like @Sergio0694 is seeing), is that correct?

Can you explain what the "x" process is in your screenshot?

Also, can you check to see if the behavior here is the same when running under a debugger vs not?  Thanks!

**Comment by JesseCol** [comment]
In the debugger, if you look at the threads that are still running, does it give any clues to why the process is still alive?

If you remove the WebView2 does the process still linger?  Adding @DmitriyKomin in case he's aware of cases where WebView2 keeps the process alive longer than expected.

**Comment by sigmarsson** [comment]
@JesseCol - Thank you for your message. I confirm #7193 deserved to be closed. I removed the control WebView2 and problem has not vanished.
