### ISSUE TITLE
When hiding titlebar a few white pixels still show on top

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#8947]
### Describe the bug

When hiding the titlebar using `OverlappedPresenter.SetBorderAndTitleBar(true, false)` a few pixels of white titlebar still shows.

### Steps to reproduce the bug

1. Create a new WinUI app.
2. in app.xaml root tag, set `RequestedTheme="Dark"`
3. in MainWindow.xaml.cs constructor add this code to hide the titlebar
```cs
            var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            Microsoft.UI.WindowId windowId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
            Microsoft.UI.Windowing.AppWindow appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
            var presenter = appWindow.Presenter as Microsoft.UI.Windowing.OverlappedPresenter;
            presenter.SetBorderAndTitleBar(true, false);
```
Run the app, and observe the white color on top of the window.

### Expected behavior

Entire window is black

### Screenshots

![image](https://user-images.githubusercontent.com/1378165/180280950-6f4a1065-c1a3-4892-b02c-14be759f324c.png)

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

First reported in WinUIEx: https://github.com/dotMorten/WinUIEx/issues/67

**Comment by riverar** [comment]
Sounds like we're in disagreement over "forever", that's fair.

Maybe we can get this documented as a known issue when using this API for future devs?

**Comment by pratikone** [comment]
Yeah, that seems right. This issue has existed for some time and affects any app which does custom titlebar. If you are quick enough, you can spot it during launch of Visual Studio too. It goes away quickly.

Let me check internally if we can make some progress on fixing this.if not, getting it documented would be a good step too. Thanks for the suggestion

**Comment by duncanmacmichael** [comment]
Fixed in 1.4.3, closing issue.

**Comment by khoabui1412** [comment]
I just tested in ver 1.4.3 but issue still remains

**Comment by dotMorten** [comment]
I see the same thing. @duncanmacmichael  Can we're open this?

**Comment by LucaCris** [comment]
Not fixed, when app is maximized:

![Screenshot 2023-12-06 104358](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/d4b40cd6-3e76-49df-a464-aa0d06f72234)

(I assure you, there is an one pixel white line on top, try to open image out of this page).

**Comment by BeaverSoftware** [comment]
> Not fixed, when app is maximized:
> 
> ![Screenshot 2023-12-06 104358](https://private-user-images.githubusercontent.com/50824617/288362705-d4b40cd6-3e76-49df-a464-aa0d06f72234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTE4MDAsIm5iZiI6MTcxMjI1MTUwMCwicGF0aCI6Ii81MDgyNDYxNy8yODgzNjI3MDUtZDRiNDBjZDYtM2U3Ni00OWRmLWE0NjQtYWEwZDA2ZjcyMjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE3MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MTBiYjQ3YWU2MzkwNTFhNTJkM2IwMWNlNGE0Yjk0OTIwZDJjNmRjZGQwMWNiMTJiNTExZWQ2MTBlMGNlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VneVOSsT7m4N3rYImQ7sxvRrP35R4CI3KWf0-E5Nk4g)
> 
> (I assure you, there is an one pixel white line on top, try to open image out of this page).

For me, the 1 pixel line problem was solved by setting it to AppWindowTitleBar.ExtendsContentIntoTitleBar instead of Window.ExtendsContentIntoTitleBar. Currently there is a problem when in full screen mode, a resize cursor appears on the outside borders of the TitleBar.

**Comment by riverar** [comment]
What is this issue a duplicate of @llongley?

**Comment by riverar** [comment]
@ranjeshj @Scottj1s Can one of you assist here? This is the millionth time @llongley has closed an issue without any commentary, and frankly it's getting very old. Have some frickin' respect for your users/customers.

**Comment by LucaCris** [comment]
@llongley I replicate every day: I have two monitors (different res/dpi), when I swap app position between them, the line appears. Do you have a similar set?

**Comment by codendone** [comment]
Looking at the internal bug, this got resolved as duplicate of #7629 (I'm guessing from the perspective of same underlying cause/fix, since the bug visibility is different).

(FYI, most of the @llongley changes are an automated tool trying to sync state between GitHub and our internal bug tracking. There is more we could do to improve the tool and our processes. We try to update manually to add missing info.)

**Comment by riverar** [comment]
Thanks a bunch @codendone, mystery solved!
